-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION postgres;
CREATE SCHEMA logging AUTHORIZATION postgres;

-- DROP SEQUENCE public.ad_domains_id_seq;
CREATE SEQUENCE public.ad_domains_id_seq INCREMENT
BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE;

-- DROP SEQUENCE public.app_ads_entrys_id_seq;
CREATE SEQUENCE public.app_ads_entrys_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;

-- DROP SEQUENCE public.app_ads_map_id_seq;
CREATE SEQUENCE public.app_ads_map_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;

-- DROP SEQUENCE public.app_urls_map_id_seq;
CREATE SEQUENCE public.app_urls_map_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.crawl_results_id_seq;

CREATE SEQUENCE public.crawl_results_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.csv_store_app_dump_id_seq;

CREATE SEQUENCE public.csv_store_app_dump_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.developers_id_seq;

CREATE SEQUENCE public.developers_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.newtable_id_seq;

CREATE SEQUENCE public.newtable_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.pub_domains_id_seq;

CREATE SEQUENCE public.pub_domains_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.store_apps_id_seq;

CREATE SEQUENCE public.store_apps_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.stores_column1_seq;

CREATE SEQUENCE public.stores_column1_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;-- public.ad_domains definition

-- Drop table

-- DROP TABLE public.ad_domains;

CREATE TABLE public.ad_domains (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "domain" varchar NOT NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT ad_domains_pkey PRIMARY KEY (id),
    CONSTRAINT ad_domains_un UNIQUE (domain)
);

-- Table Triggers

CREATE TRIGGER ad_domains_updated_at BEFORE
UPDATE
ON
public.ad_domains FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.crawl_results definition

-- Drop table

-- DROP TABLE public.crawl_results;

CREATE TABLE public.crawl_results (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outcome varchar NULL,
    CONSTRAINT crawl_results_pkey PRIMARY KEY (id)
);


-- public.platforms definition

-- Drop table

-- DROP TABLE public.platforms;

CREATE TABLE public.platforms (
    id int4 NOT NULL DEFAULT nextval('newtable_id_seq'::regclass),
    "name" varchar NOT NULL,
    CONSTRAINT platforms_pk PRIMARY KEY (id),
    CONSTRAINT platforms_un UNIQUE (name)
);


-- public.app_ads_entrys definition

-- Drop table

-- DROP TABLE public.app_ads_entrys;

CREATE TABLE public.app_ads_entrys (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ad_domain int4 NOT NULL,
    publisher_id varchar NOT NULL,
    relationship varchar NOT NULL,
    certification_auth varchar NULL,
    notes varchar NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT app_ads_entrys_pkey PRIMARY KEY (id),
    CONSTRAINT app_ads_txt_un UNIQUE (ad_domain, publisher_id, relationship),
    CONSTRAINT app_ads_txt_fk FOREIGN KEY (
        ad_domain
    ) REFERENCES public.ad_domains (id)
);

-- Table Triggers

CREATE TRIGGER app_ads_entrys_updated_at BEFORE
UPDATE
ON
public.app_ads_entrys FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.pub_domains definition

-- Drop table

-- DROP TABLE public.pub_domains;

CREATE TABLE public.pub_domains (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    url varchar NOT NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    crawl_result int4 NULL,
    crawled_at timestamp NULL,
    CONSTRAINT pub_domains_pkey PRIMARY KEY (id),
    CONSTRAINT pub_domains_un UNIQUE (url),
    CONSTRAINT pub_domains_fk FOREIGN KEY (
        crawl_result
    ) REFERENCES public.crawl_results (id)
);

-- Table Triggers

CREATE TRIGGER pub_domains_crawled_at BEFORE
UPDATE
OF crawl_result ON
public.pub_domains FOR EACH ROW EXECUTE FUNCTION update_crawled_at();
CREATE TRIGGER pub_domains_updated_at BEFORE
UPDATE
ON
public.pub_domains FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.stores definition

-- Drop table

-- DROP TABLE public.stores;

CREATE TABLE public.stores (
    id int4 NOT NULL DEFAULT nextval('stores_column1_seq'::regclass),
    "name" varchar NOT NULL,
    platform int4 NULL,
    CONSTRAINT stores_pk PRIMARY KEY (id),
    CONSTRAINT stores_un UNIQUE (name),
    CONSTRAINT stores_fk FOREIGN KEY (platform) REFERENCES public.platforms (id)
);


-- public.app_ads_map definition

-- Drop table

-- DROP TABLE public.app_ads_map;

CREATE TABLE public.app_ads_map (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pub_domain int4 NOT NULL,
    app_ads_entry int4 NOT NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT app_ads_map_pkey PRIMARY KEY (id),
    CONSTRAINT app_ads_map_un UNIQUE (pub_domain, app_ads_entry),
    CONSTRAINT app_ads_map_fk FOREIGN KEY (
        app_ads_entry
    ) REFERENCES public.app_ads_entrys (id),
    CONSTRAINT app_ads_map_fk_1 FOREIGN KEY (
        pub_domain
    ) REFERENCES public.pub_domains (id)
);

-- Table Triggers

CREATE TRIGGER app_ads_map_updated_at BEFORE
UPDATE
ON
public.app_ads_map FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.app_store_csv_dump definition

-- Drop table

-- DROP TABLE public.app_store_csv_dump;

CREATE TABLE public.app_store_csv_dump (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    platform int4 NOT NULL,
    store int4 NOT NULL,
    app_name text NULL,
    app_id text NOT NULL,
    category text NULL,
    rating float8 NULL,
    rating_count float8 NULL,
    installs text NULL,
    minimum_installs float8 NULL,
    maximum_installs int8 NULL,
    "free" bool NULL,
    price float8 NULL,
    currency text NULL,
    "size" text NULL,
    minimum_android text NULL,
    developer_id text NULL,
    developer_website text NULL,
    developer_email text NULL,
    released text NULL,
    last_updated text NULL,
    content_rating text NULL,
    privacy_policy text NULL,
    ad_supported bool NULL,
    in_app_purchases bool NULL,
    editors_choice bool NULL,
    CONSTRAINT csv_store_app_dump_pkey PRIMARY KEY (id),
    CONSTRAINT csv_store_app_dump_un UNIQUE (platform, store, app_id),
    CONSTRAINT csv_store_app_dump_fk FOREIGN KEY (
        platform
    ) REFERENCES public.platforms (id),
    CONSTRAINT csv_store_app_dump_fk_01 FOREIGN KEY (
        store
    ) REFERENCES public.stores (id)
);
