-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION postgres;
CREATE SCHEMA logging AUTHORIZATION postgres;

-- DROP SEQUENCE public.ad_domains_id_seq;
CREATE SEQUENCE public.ad_domains_id_seq INCREMENT
BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE;

-- DROP SEQUENCE public.app_ads_entrys_id_seq;
CREATE SEQUENCE public.app_ads_entrys_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;

-- DROP SEQUENCE public.app_ads_map_id_seq;
CREATE SEQUENCE public.app_ads_map_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;

-- DROP SEQUENCE public.app_urls_map_id_seq;
CREATE SEQUENCE public.app_urls_map_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.crawl_results_id_seq;

CREATE SEQUENCE public.crawl_results_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.csv_store_app_dump_id_seq;

CREATE SEQUENCE public.csv_store_app_dump_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.developers_id_seq;

CREATE SEQUENCE public.developers_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.newtable_id_seq;

CREATE SEQUENCE public.newtable_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.pub_domains_id_seq;

CREATE SEQUENCE public.pub_domains_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.store_apps_id_seq;

CREATE SEQUENCE public.store_apps_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
-- DROP SEQUENCE public.stores_column1_seq;

CREATE SEQUENCE public.stores_column1_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;-- public.ad_domains definition

-- Drop table

-- DROP TABLE public.ad_domains;

CREATE TABLE public.ad_domains (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "domain" varchar NOT NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT ad_domains_pkey PRIMARY KEY (id),
    CONSTRAINT ad_domains_un UNIQUE (domain)
);

-- Table Triggers

CREATE TRIGGER ad_domains_updated_at BEFORE
UPDATE
ON
public.ad_domains FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.crawl_results definition

-- Drop table

-- DROP TABLE public.crawl_results;

CREATE TABLE public.crawl_results (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outcome varchar NULL,
    CONSTRAINT crawl_results_pkey PRIMARY KEY (id)
);


-- public.platforms definition

-- Drop table

-- DROP TABLE public.platforms;

CREATE TABLE public.platforms (
    id int4 NOT NULL DEFAULT nextval('newtable_id_seq'::regclass),
    "name" varchar NOT NULL,
    CONSTRAINT platforms_pk PRIMARY KEY (id),
    CONSTRAINT platforms_un UNIQUE (name)
);


-- public.app_ads_entrys definition

-- Drop table

-- DROP TABLE public.app_ads_entrys;

CREATE TABLE public.app_ads_entrys (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ad_domain int4 NOT NULL,
    publisher_id varchar NOT NULL,
    relationship varchar NOT NULL,
    certification_auth varchar NULL,
    notes varchar NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT app_ads_entrys_pkey PRIMARY KEY (id),
    CONSTRAINT app_ads_txt_un UNIQUE (ad_domain, publisher_id, relationship),
    CONSTRAINT app_ads_txt_fk FOREIGN KEY (
        ad_domain
    ) REFERENCES public.ad_domains (id)
);

-- Table Triggers

CREATE TRIGGER app_ads_entrys_updated_at BEFORE
UPDATE
ON
public.app_ads_entrys FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.pub_domains definition

-- Drop table

-- DROP TABLE public.pub_domains;

CREATE TABLE public.pub_domains (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    url varchar NOT NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    crawl_result int4 NULL,
    crawled_at timestamp NULL,
    CONSTRAINT pub_domains_pkey PRIMARY KEY (id),
    CONSTRAINT pub_domains_un UNIQUE (url),
    CONSTRAINT pub_domains_fk FOREIGN KEY (
        crawl_result
    ) REFERENCES public.crawl_results (id)
);

-- Table Triggers

CREATE TRIGGER pub_domains_crawled_at BEFORE
UPDATE
OF crawl_result ON
public.pub_domains FOR EACH ROW EXECUTE FUNCTION update_crawled_at();
CREATE TRIGGER pub_domains_updated_at BEFORE
UPDATE
ON
public.pub_domains FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.stores definition

-- Drop table

-- DROP TABLE public.stores;

CREATE TABLE public.stores (
    id int4 NOT NULL DEFAULT nextval('stores_column1_seq'::regclass),
    "name" varchar NOT NULL,
    platform int4 NULL,
    CONSTRAINT stores_pk PRIMARY KEY (id),
    CONSTRAINT stores_un UNIQUE (name),
    CONSTRAINT stores_fk FOREIGN KEY (platform) REFERENCES public.platforms (id)
);


-- public.app_ads_map definition

-- Drop table

-- DROP TABLE public.app_ads_map;

CREATE TABLE public.app_ads_map (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pub_domain int4 NOT NULL,
    app_ads_entry int4 NOT NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT app_ads_map_pkey PRIMARY KEY (id),
    CONSTRAINT app_ads_map_un UNIQUE (pub_domain, app_ads_entry),
    CONSTRAINT app_ads_map_fk FOREIGN KEY (
        app_ads_entry
    ) REFERENCES public.app_ads_entrys (id),
    CONSTRAINT app_ads_map_fk_1 FOREIGN KEY (
        pub_domain
    ) REFERENCES public.pub_domains (id)
);

-- Table Triggers

CREATE TRIGGER app_ads_map_updated_at BEFORE
UPDATE
ON
public.app_ads_map FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.app_store_csv_dump definition

-- Drop table

-- DROP TABLE public.app_store_csv_dump;

CREATE TABLE public.app_store_csv_dump (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    platform int4 NOT NULL,
    store int4 NOT NULL,
    app_name text NULL,
    app_id text NOT NULL,
    category text NULL,
    rating float8 NULL,
    rating_count float8 NULL,
    installs text NULL,
    minimum_installs float8 NULL,
    maximum_installs int8 NULL,
    "free" bool NULL,
    price float8 NULL,
    currency text NULL,
    "size" text NULL,
    minimum_android text NULL,
    developer_id text NULL,
    developer_website text NULL,
    developer_email text NULL,
    released text NULL,
    last_updated text NULL,
    content_rating text NULL,
    privacy_policy text NULL,
    ad_supported bool NULL,
    in_app_purchases bool NULL,
    editors_choice bool NULL,
    CONSTRAINT csv_store_app_dump_pkey PRIMARY KEY (id),
    CONSTRAINT csv_store_app_dump_un UNIQUE (platform, store, app_id),
    CONSTRAINT csv_store_app_dump_fk FOREIGN KEY (
        platform
    ) REFERENCES public.platforms (id),
    CONSTRAINT csv_store_app_dump_fk_01 FOREIGN KEY (
        store
    ) REFERENCES public.stores (id)
);


-- public.developers definition

-- Drop table

-- DROP TABLE public.developers;

CREATE TABLE public.developers (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    store int4 NOT NULL,
    "name" varchar NULL,
    developer_id varchar NOT NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT developers_pkey PRIMARY KEY (id),
    CONSTRAINT developers_un UNIQUE (store, developer_id),
    CONSTRAINT developers_fk FOREIGN KEY (store) REFERENCES public.stores (id)
);
CREATE INDEX developers_name_idx ON developers USING gin (
    to_tsvector('simple', name)
);
CREATE INDEX developers_developer_id_idx ON public.developers (developer_id);


CREATE TABLE store_collections (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    store int4 NOT NULL,
    collection varchar NOT NULL,
    CONSTRAINT store_collections_pk PRIMARY KEY (id),
    CONSTRAINT store_collections_fk FOREIGN KEY (
        store
    ) REFERENCES public.stores (id),
    CONSTRAINT store_collections_un UNIQUE (
        store,
        collection
    )
);


CREATE TABLE store_categories (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    store int4 NOT NULL,
    category varchar NOT NULL,
    CONSTRAINT store_categories_pk PRIMARY KEY (id),
    CONSTRAINT store_categories_fk FOREIGN KEY (
        store
    ) REFERENCES public.stores (id),
    CONSTRAINT store_categories_un UNIQUE (
        store,
        category
    )
);

CREATE TABLE app_rankings (
    id serial PRIMARY KEY,
    crawled_date date NOT NULL,
    country int NOT NULL,
    store int NOT NULL,
    store_collection int NOT NULL,
    store_category int NOT NULL,
    "rank" int NOT NULL,
    store_app int NOT NULL,
    CONSTRAINT fk_store FOREIGN KEY (store) REFERENCES stores (id),
    CONSTRAINT fk_store_collection FOREIGN KEY (
        store_collection
    ) REFERENCES store_collections (id),
    CONSTRAINT fk_store_category FOREIGN KEY (
        store_category
    ) REFERENCES store_categories (id),
    CONSTRAINT fk_country FOREIGN KEY (country) REFERENCES countries (id),
    CONSTRAINT fk_store_app FOREIGN KEY (store_app) REFERENCES store_apps (id),
    CONSTRAINT unique_ranking UNIQUE (
        crawled_date, country,
        "rank",
        store,
        store_collection,
        store_category
    )
);


-- DROP TABLE public.store_apps;
CREATE TABLE store_apps (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    developer int4 NULL,
    "name" varchar NULL,
    store_id varchar NOT NULL,
    store int4 NOT NULL,
    category varchar NULL,
    rating float8 NULL,
    rating_count int NULL,
    review_count float8 NULL,
    installs float8 NULL,
    "free" bool NULL,
    price float8 NULL,
    "size" text NULL,
    minimum_android text NULL,
    developer_email text NULL,
    store_last_updated timestamp NULL,
    content_rating text NULL,
    ad_supported bool NULL,
    in_app_purchases bool NULL,
    editors_choice bool NULL,
    icon_url_512 varchar NULL,
    featured_image_url varchar NULL,
    phone_image_url_1 varchar NULL,
    phone_image_url_2 varchar NULL,
    phone_image_url_3 varchar NULL,
    tablet_image_url_1 varchar NULL,
    tablet_image_url_2 varchar NULL,
    tablet_image_url_3 varchar NULL,
    release_date date NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    crawl_result int4 NULL,
    CONSTRAINT store_apps_pkey PRIMARY KEY (id),
    CONSTRAINT store_apps_un UNIQUE (store, store_id),
    CONSTRAINT store_apps_fk FOREIGN KEY (store) REFERENCES public.stores (id),
    CONSTRAINT store_apps_fk_03 FOREIGN KEY (
        crawl_result
    ) REFERENCES public.crawl_results (id),
    CONSTRAINT store_apps_fk_1 FOREIGN KEY (
        developer
    ) REFERENCES public.developers (id)
);

CREATE INDEX store_apps_updated_at_idx ON public.store_apps USING btree (
    updated_at
);
CREATE INDEX store_apps_store_id_idx ON public.store_apps USING btree (
    store_id
);
CREATE INDEX store_apps_name_idx ON store_apps USING gin (
    to_tsvector('simple', name)
);




-- Table Triggers
CREATE TRIGGER developers_updated_at BEFORE
UPDATE
ON
public.developers FOR EACH ROW EXECUTE FUNCTION update_modified_column();



-- public.store_apps_history definition

--DROP TABLE IF EXISTS store_apps_history;
CREATE TABLE store_apps_history (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    store_app int REFERENCES store_apps (id),
    installs float8 NULL,
    review_count float8 NULL,
    rating float8 NULL,
    crawled_date date DEFAULT current_date,
    CONSTRAINT store_apps_history_pkey PRIMARY KEY (id),
    CONSTRAINT store_apps_history_un UNIQUE (store_app, crawled_date),
    CONSTRAINT store_apps_history_fk FOREIGN KEY (
        store_app
    ) REFERENCES public.store_apps (id)
);

-- public.store_apps_country_history definition

-- Drop table

-- DROP TABLE public.store_apps_country_history;

CREATE TABLE public.store_apps_country_history (
    store_app int4 NOT NULL,
    review_count float8 NULL,
    rating float8 NULL,
    crawled_date date NULL,
    rating_count int4 NULL,
    histogram _int8 NULL DEFAULT ARRAY[]::integer [],
    installs int4 NULL,
    country varchar(2) NOT NULL DEFAULT 'US'::character varying,
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE
    ),
    CONSTRAINT store_apps_country_history_pk PRIMARY KEY (id),
    CONSTRAINT store_apps_country_history_un UNIQUE (
        store_app, country, crawled_date
    ),
    CONSTRAINT store_apps_country_history_app_fk FOREIGN KEY (
        store_app
    ) REFERENCES public.store_apps (id),
    CONSTRAINT store_apps_country_history_fk FOREIGN KEY (
        country
    ) REFERENCES public.countries (alpha2)
);


-- logging.developers_crawled_at definition

-- Drop table

-- DROP TABLE logging.developers_crawled_at;

CREATE TABLE logging.developers_crawled_at (
    developer int4 NOT NULL,
    apps_crawled_at timestamp NULL,
    CONSTRAINT developers_crawled_at_pk PRIMARY KEY (developer),
    CONSTRAINT newtable_fk FOREIGN KEY (
        developer
    ) REFERENCES public.developers (id)
);

-- logging.developers_crawled_at definition

-- Drop table

-- DROP TABLE logging.developers_crawled_at;

CREATE TABLE logging.store_app_sources (
    store int2 NOT NULL,
    store_app int4 NOT NULL,
    crawl_source text NULL,
    CONSTRAINT store_app_sources_pk PRIMARY KEY (store, store_app),
    CONSTRAINT store_app_sources_store_fk FOREIGN KEY (
        store
    ) REFERENCES public.stores (id),
    CONSTRAINT store_app_sources_app_fk FOREIGN KEY (
        store_app
    ) REFERENCES public.store_apps (id) ON DELETE CASCADE
);




-- Table Triggers

CREATE TRIGGER store_app_audit AFTER
INSERT
OR
DELETE
OR
UPDATE
ON
public.store_apps FOR EACH ROW EXECUTE FUNCTION process_store_app_audit();
CREATE TRIGGER store_apps_updated_at BEFORE
UPDATE
ON
public.store_apps FOR EACH ROW EXECUTE FUNCTION update_modified_column();


-- public.app_urls_map definition

-- Drop table

-- DROP TABLE public.app_urls_map;

CREATE TABLE public.app_urls_map (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    store_app int4 NOT NULL,
    pub_domain int4 NOT NULL,
    created_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT app_urls_map_pkey PRIMARY KEY (id),
    CONSTRAINT app_urls_un UNIQUE (store_app),
    CONSTRAINT app_urls_fk FOREIGN KEY (
        store_app
    ) REFERENCES public.store_apps (id),
    CONSTRAINT app_urls_fk_1 FOREIGN KEY (
        pub_domain
    ) REFERENCES public.pub_domains (id)
);

-- Table Triggers

CREATE TRIGGER app_urls_map_updated_at BEFORE
UPDATE
ON
public.app_urls_map FOR EACH ROW EXECUTE FUNCTION update_modified_column();


CREATE TABLE version_codes (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    store_app integer NOT NULL,
    version_code integer NOT NULL,
    crawl_result smallint NOT NULL,
    updated_at timestamp NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT version_codes_pkey PRIMARY KEY (id),
    CONSTRAINT version_codes_un UNIQUE (store_app, version_code),
    CONSTRAINT vc_fk_store_app FOREIGN KEY (store_app) REFERENCES store_apps (
        id
    )
);

CREATE TABLE version_details (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    version_code integer NOT NULL,
    xml_path text NOT NULL,
    tag text,
    android_name text,
    CONSTRAINT version_details_pkey PRIMARY KEY (id),
    CONSTRAINT fk_vd_version_code FOREIGN KEY (
        version_code
    ) REFERENCES version_codes (id)
);

-- ISO 3166 countries to PostgreSQL
CREATE TABLE IF NOT EXISTS countries (
    id int4 NOT NULL,
    alpha2 varchar(2) NOT NULL,
    alpha3 varchar(3) NOT NULL,
    langcs varchar(45) NOT NULL,
    langde varchar(45) NOT NULL,
    langen varchar(45) NOT NULL,
    langes varchar(45) NOT NULL,
    langfr varchar(45) NOT NULL,
    langit varchar(45) NOT NULL,
    langnl varchar(45) NOT NULL,
    CONSTRAINT countries_pk PRIMARY KEY (id),
    CONSTRAINT countries_al2 UNIQUE (alpha2),
    CONSTRAINT countries_al3 UNIQUE (alpha3)
);


CREATE TABLE public.trackers (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    CONSTRAINT trackers_pk PRIMARY KEY (id)
);


CREATE TABLE public.tracker_package_map (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tracker int4 NOT NULL,
    package_pattern varchar NOT NULL,
    CONSTRAINT tracker_package_map_pk PRIMARY KEY (id),
    CONSTRAINT fk_tracker_pkg_map FOREIGN KEY (
        tracker
    ) REFERENCES trackers (id)
);


CREATE TABLE public.networks (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    CONSTRAINT networks_pk PRIMARY KEY (id)
);


CREATE TABLE public.network_package_map (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    network int4 NOT NULL,
    package_pattern varchar NOT NULL,
    CONSTRAINT network_package_map_pk PRIMARY KEY (id),
    CONSTRAINT fk_network_pkg_map FOREIGN KEY (
        network
    ) REFERENCES networks (id)
);
