-- ISO 3166 countries to PostgreSQL
CREATE TABLE IF NOT EXISTS countries (
    id int4 NOT NULL,
    alpha2 varchar(2) NOT NULL,
    alpha3 varchar(3) NOT NULL,
    langcs varchar(45) NOT NULL,
    langde varchar(45) NOT NULL,
    langen varchar(45) NOT NULL,
    langes varchar(45) NOT NULL,
    langfr varchar(45) NOT NULL,
    langit varchar(45) NOT NULL,
    langnl varchar(45) NOT NULL,
    CONSTRAINT countries_pk PRIMARY KEY (id),
    CONSTRAINT countries_al2 UNIQUE (alpha2),
    CONSTRAINT countries_al3 UNIQUE (alpha3)
);


CREATE TABLE public.trackers (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    CONSTRAINT trackers_pk PRIMARY KEY (id)
);


CREATE TABLE public.tracker_package_map (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tracker int4 NOT NULL,
    package_pattern varchar NOT NULL,
    CONSTRAINT tracker_package_map_pk PRIMARY KEY (id),
    CONSTRAINT fk_tracker_pkg_map FOREIGN KEY (
        tracker
    ) REFERENCES trackers (id)
);


CREATE TABLE public.networks (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    CONSTRAINT networks_pk PRIMARY KEY (id)
);


CREATE TABLE public.network_package_map (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    network int4 NOT NULL,
    package_pattern varchar NOT NULL,
    CONSTRAINT network_package_map_pk PRIMARY KEY (id),
    CONSTRAINT fk_network_pkg_map FOREIGN KEY (
        network
    ) REFERENCES networks (id)
);
