--
-- PostgreSQL database dump
--

\restrict UjIPKEvOoEphl49BKsMGb2aIbL6cdBW5AKc7A2FfzVM7Nb09uE2Uq1lUfihQrrP

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: adtech; Owner: postgres
--

CREATE TABLE adtech.categories (
    id integer NOT NULL,
    name character varying NOT NULL,
    url_slug character varying
);


ALTER TABLE adtech.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: adtech; Owner: postgres
--

ALTER TABLE adtech.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME adtech.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict UjIPKEvOoEphl49BKsMGb2aIbL6cdBW5AKc7A2FfzVM7Nb09uE2Uq1lUfihQrrP

