--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: companies; Type: TABLE; Schema: adtech; Owner: postgres
--

CREATE TABLE adtech.companies (
    id integer NOT NULL,
    name character varying NOT NULL,
    parent_company_id integer,
    description text,
    domain_id integer NOT NULL
);


ALTER TABLE adtech.companies OWNER TO postgres;

--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: adtech; Owner: postgres
--

ALTER TABLE adtech.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME adtech.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies companies_domain_unique; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.companies
    ADD CONSTRAINT companies_domain_unique UNIQUE (domain_id);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: companies unique_company_name; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.companies
    ADD CONSTRAINT unique_company_name UNIQUE (name);


--
-- Name: companies fk_ad_domain_id; Type: FK CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.companies
    ADD CONSTRAINT fk_ad_domain_id FOREIGN KEY (domain_id) REFERENCES public.ad_domains(id);


--
-- Name: companies fk_companies_parent; Type: FK CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.companies
    ADD CONSTRAINT fk_companies_parent FOREIGN KEY (parent_company_id) REFERENCES adtech.companies(id);


--
-- PostgreSQL database dump complete
--

