--
-- PostgreSQL database dump
--

\restrict WckPxCKb3ZHFHS0ele2nJu3oha98LhlOag37dmF0gdphmXEbFckAbhX3pRh6FHE

-- Dumped from database version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sdk_packages; Type: TABLE; Schema: adtech; Owner: postgres
--

CREATE TABLE adtech.sdk_packages (
    id integer NOT NULL,
    package_pattern character varying NOT NULL,
    sdk_id integer
);


ALTER TABLE adtech.sdk_packages OWNER TO postgres;

--
-- Name: sdk_packages_id_seq; Type: SEQUENCE; Schema: adtech; Owner: postgres
--

ALTER TABLE adtech.sdk_packages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME adtech.sdk_packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sdk_packages sdk_packages_pkey; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_packages
ADD CONSTRAINT sdk_packages_pkey PRIMARY KEY (id);


--
-- Name: sdk_packages unique_package_pattern; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_packages
ADD CONSTRAINT unique_package_pattern UNIQUE (package_pattern);


--
-- Name: sdk_packages_package_pattern_idx; Type: INDEX; Schema: adtech; Owner: postgres
--

CREATE INDEX sdk_packages_package_pattern_idx ON adtech.sdk_packages USING btree (
    package_pattern
);


--
-- Name: sdk_packages sdk_packages_sdk_id_fkey; Type: FK CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_packages
ADD CONSTRAINT sdk_packages_sdk_id_fkey FOREIGN KEY (
    sdk_id
) REFERENCES adtech.sdks (id);


--
-- PostgreSQL database dump complete
--

\unrestrict WckPxCKb3ZHFHS0ele2nJu3oha98LhlOag37dmF0gdphmXEbFckAbhX3pRh6FHE
