--
-- PostgreSQL database dump
--

\restrict f6og5qMazywBdB4c14z6ZO2vkxrJJsxxHg3IJ9RbIiEKZR8DvIesWNI7cE3b9LJ

-- Dumped from database version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)
-- Dumped by pg_dump version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sdk_paths; Type: TABLE; Schema: adtech; Owner: postgres
--

CREATE TABLE adtech.sdk_paths (
    id integer NOT NULL,
    path_pattern character varying NOT NULL,
    sdk_id integer
);


ALTER TABLE adtech.sdk_paths OWNER TO postgres;

--
-- Name: sdk_paths_id_seq; Type: SEQUENCE; Schema: adtech; Owner: postgres
--

ALTER TABLE adtech.sdk_paths ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME adtech.sdk_paths_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sdk_paths sdk_pathss_pkey; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_paths
    ADD CONSTRAINT sdk_pathss_pkey PRIMARY KEY (id);


--
-- Name: sdk_paths unique_path_pattern; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_paths
    ADD CONSTRAINT unique_path_pattern UNIQUE (path_pattern);


--
-- Name: sdk_path_pattern_idx; Type: INDEX; Schema: adtech; Owner: postgres
--

CREATE INDEX sdk_path_pattern_idx ON adtech.sdk_paths USING btree (path_pattern);


--
-- Name: sdk_paths_path_pattern_trgm_idx; Type: INDEX; Schema: adtech; Owner: postgres
--

CREATE INDEX sdk_paths_path_pattern_trgm_idx ON adtech.sdk_paths USING gin (lower((path_pattern)::text) public.gin_trgm_ops);


--
-- Name: sdk_paths sdk_paths_sdk_id_fkey; Type: FK CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_paths
    ADD CONSTRAINT sdk_paths_sdk_id_fkey FOREIGN KEY (sdk_id) REFERENCES adtech.sdks(id);


--
-- PostgreSQL database dump complete
--

\unrestrict f6og5qMazywBdB4c14z6ZO2vkxrJJsxxHg3IJ9RbIiEKZR8DvIesWNI7cE3b9LJ

