--
-- PostgreSQL database dump
--

\restrict 4J05zVaKnlBmlwH7SsWx1vDxK7eNgFa5GQwShjcS3a8MuqaaOYKvVyqDqYbvPSW

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sdk_packages; Type: TABLE; Schema: adtech; Owner: postgres
--

CREATE TABLE adtech.sdk_packages (
    id integer NOT NULL,
    package_pattern character varying NOT NULL,
    sdk_id integer
);


ALTER TABLE adtech.sdk_packages OWNER TO postgres;

--
-- Name: sdk_packages_id_seq; Type: SEQUENCE; Schema: adtech; Owner: postgres
--

ALTER TABLE adtech.sdk_packages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME adtech.sdk_packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sdk_packages sdk_packages_pkey; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_packages
    ADD CONSTRAINT sdk_packages_pkey PRIMARY KEY (id);


--
-- Name: sdk_packages unique_package_pattern; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_packages
    ADD CONSTRAINT unique_package_pattern UNIQUE (package_pattern);


--
-- Name: sdk_packages_package_pattern_idx; Type: INDEX; Schema: adtech; Owner: postgres
--

CREATE INDEX sdk_packages_package_pattern_idx ON adtech.sdk_packages USING btree (package_pattern);


--
-- Name: sdk_packages_pattern_lower_idx; Type: INDEX; Schema: adtech; Owner: postgres
--

CREATE INDEX sdk_packages_pattern_lower_idx ON adtech.sdk_packages USING btree (lower((package_pattern)::text) text_pattern_ops);


--
-- Name: sdk_packages_pattern_trgm_idx; Type: INDEX; Schema: adtech; Owner: postgres
--

CREATE INDEX sdk_packages_pattern_trgm_idx ON adtech.sdk_packages USING gin (lower((package_pattern)::text) public.gin_trgm_ops);


--
-- Name: sdk_packages sdk_packages_sdk_id_fkey; Type: FK CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdk_packages
    ADD CONSTRAINT sdk_packages_sdk_id_fkey FOREIGN KEY (sdk_id) REFERENCES adtech.sdks(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 4J05zVaKnlBmlwH7SsWx1vDxK7eNgFa5GQwShjcS3a8MuqaaOYKvVyqDqYbvPSW

