--
-- PostgreSQL database dump
--

\restrict HtEfOrTm3zDhk8mkdgzQkJs2g0uFNxIUfa63EKUpdbXIpeeY0YSdI9EXlb1NlNN

-- Dumped from database version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)
-- Dumped by pg_dump version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sdks; Type: TABLE; Schema: adtech; Owner: postgres
--

CREATE TABLE adtech.sdks (
    id integer NOT NULL,
    company_id integer NOT NULL,
    sdk_name character varying(255) NOT NULL,
    sdk_url character varying(255),
    is_open_source boolean DEFAULT false,
    has_third_party_tracking boolean DEFAULT true,
    license_type character varying(50) DEFAULT 'Commercial'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sdk_slug text
);


ALTER TABLE adtech.sdks OWNER TO postgres;

--
-- Name: sdks_id_seq; Type: SEQUENCE; Schema: adtech; Owner: postgres
--

ALTER TABLE adtech.sdks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME adtech.sdks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sdks sdks_company_id_sdk_name_key; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdks
    ADD CONSTRAINT sdks_company_id_sdk_name_key UNIQUE (company_id, sdk_name);


--
-- Name: sdks sdks_pkey; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdks
    ADD CONSTRAINT sdks_pkey PRIMARY KEY (id);


--
-- Name: sdks unique_sdk_slug; Type: CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdks
    ADD CONSTRAINT unique_sdk_slug UNIQUE (sdk_slug);


--
-- Name: sdks sdks_company_id_fkey; Type: FK CONSTRAINT; Schema: adtech; Owner: postgres
--

ALTER TABLE ONLY adtech.sdks
    ADD CONSTRAINT sdks_company_id_fkey FOREIGN KEY (company_id) REFERENCES adtech.companies(id);


--
-- PostgreSQL database dump complete
--

\unrestrict HtEfOrTm3zDhk8mkdgzQkJs2g0uFNxIUfa63EKUpdbXIpeeY0YSdI9EXlb1NlNN

