--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ad_domains; Type: TABLE; Schema: public; Owner: james
--

CREATE TABLE public.ad_domains (
    id integer NOT NULL,
    domain character varying NOT NULL,
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now())
);


ALTER TABLE public.ad_domains OWNER TO james;

--
-- Name: ad_domains_id_seq; Type: SEQUENCE; Schema: public; Owner: james
--

ALTER TABLE public.ad_domains ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ad_domains_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ad_domains ad_domains_pkey; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.ad_domains
ADD CONSTRAINT ad_domains_pkey PRIMARY KEY (id);


--
-- Name: ad_domains ad_domains_un; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.ad_domains
ADD CONSTRAINT ad_domains_un UNIQUE (domain);


--
-- Name: ad_domains ad_domains_updated_at; Type: TRIGGER; Schema: public; Owner: james
--

CREATE TRIGGER ad_domains_updated_at BEFORE UPDATE ON public.ad_domains FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();


--
-- PostgreSQL database dump complete
--
