--
-- PostgreSQL database dump
--

\restrict MMgfwDVgvTX04GuLihnwhYMhV8AuhbgkCjrJCxKCbl8QPqrzwtaB2U3NEKxb5BH

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_ads_entrys; Type: TABLE; Schema: public; Owner: james
--

CREATE TABLE public.app_ads_entrys (
    id integer NOT NULL,
    ad_domain integer NOT NULL,
    publisher_id character varying NOT NULL,
    relationship character varying NOT NULL,
    certification_auth character varying,
    notes character varying,
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now())
);


ALTER TABLE public.app_ads_entrys OWNER TO james;

--
-- Name: app_ads_entrys_id_seq; Type: SEQUENCE; Schema: public; Owner: james
--

ALTER TABLE public.app_ads_entrys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_ads_entrys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_ads_entrys app_ads_entrys_pkey; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.app_ads_entrys
    ADD CONSTRAINT app_ads_entrys_pkey PRIMARY KEY (id);


--
-- Name: app_ads_entrys app_ads_txt_un; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.app_ads_entrys
    ADD CONSTRAINT app_ads_txt_un UNIQUE (ad_domain, publisher_id, relationship);


--
-- Name: app_ads_entrys app_ads_entrys_updated_at; Type: TRIGGER; Schema: public; Owner: james
--

CREATE TRIGGER app_ads_entrys_updated_at BEFORE UPDATE ON public.app_ads_entrys FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();


--
-- Name: app_ads_entrys app_ads_entrys_domain_fk; Type: FK CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.app_ads_entrys
    ADD CONSTRAINT app_ads_entrys_domain_fk FOREIGN KEY (ad_domain) REFERENCES public.domains(id);


--
-- PostgreSQL database dump complete
--

\unrestrict MMgfwDVgvTX04GuLihnwhYMhV8AuhbgkCjrJCxKCbl8QPqrzwtaB2U3NEKxb5BH

