--
-- PostgreSQL database dump
--

\restrict sfHmYhfxxVAgQxltIyehXLR7dxd8nBhQKvgOzd3z0OIJgLk6puLHpt0I3AstTZ4

-- Dumped from database version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)
-- Dumped by pg_dump version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: developers; Type: TABLE; Schema: public; Owner: james
--

CREATE TABLE public.developers (
    id integer NOT NULL,
    store integer NOT NULL,
    name character varying,
    developer_id character varying NOT NULL,
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    textsearchable_index_col tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, (COALESCE(name, ''::character varying))::text)) STORED
);


ALTER TABLE public.developers OWNER TO james;

--
-- Name: developers_id_seq; Type: SEQUENCE; Schema: public; Owner: james
--

ALTER TABLE public.developers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.developers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: developers developers_pkey; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.developers
    ADD CONSTRAINT developers_pkey PRIMARY KEY (id);


--
-- Name: developers developers_un; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.developers
    ADD CONSTRAINT developers_un UNIQUE (store, developer_id);


--
-- Name: dev_textsearch_generated_idx; Type: INDEX; Schema: public; Owner: james
--

CREATE INDEX dev_textsearch_generated_idx ON public.developers USING gin (textsearchable_index_col);


--
-- Name: developers_developer_id_idx; Type: INDEX; Schema: public; Owner: james
--

CREATE INDEX developers_developer_id_idx ON public.developers USING btree (developer_id);


--
-- Name: developers_name_idx; Type: INDEX; Schema: public; Owner: james
--

CREATE INDEX developers_name_idx ON public.developers USING gin (to_tsvector('simple'::regconfig, (name)::text));


--
-- Name: developers developers_updated_at; Type: TRIGGER; Schema: public; Owner: james
--

CREATE TRIGGER developers_updated_at BEFORE UPDATE ON public.developers FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();


--
-- Name: developers developers_fk; Type: FK CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.developers
    ADD CONSTRAINT developers_fk FOREIGN KEY (store) REFERENCES public.stores(id);


--
-- PostgreSQL database dump complete
--

\unrestrict sfHmYhfxxVAgQxltIyehXLR7dxd8nBhQKvgOzd3z0OIJgLk6puLHpt0I3AstTZ4

