--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: pub_domains; Type: TABLE; Schema: public; Owner: james
--

CREATE TABLE public.pub_domains (
    id integer NOT NULL,
    url character varying NOT NULL,
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    crawl_result integer,
    crawled_at timestamp without time zone
);


ALTER TABLE public.pub_domains OWNER TO james;

--
-- Name: pub_domains_id_seq; Type: SEQUENCE; Schema: public; Owner: james
--

ALTER TABLE public.pub_domains ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pub_domains_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pub_domains pub_domains_pkey; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.pub_domains
    ADD CONSTRAINT pub_domains_pkey PRIMARY KEY (id);


--
-- Name: pub_domains pub_domains_un; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.pub_domains
    ADD CONSTRAINT pub_domains_un UNIQUE (url);


--
-- Name: pub_domains pub_domains_crawled_at; Type: TRIGGER; Schema: public; Owner: james
--

CREATE TRIGGER pub_domains_crawled_at BEFORE UPDATE OF crawl_result ON public.pub_domains FOR EACH ROW EXECUTE FUNCTION public.update_crawled_at();


--
-- Name: pub_domains pub_domains_updated_at; Type: TRIGGER; Schema: public; Owner: james
--

CREATE TRIGGER pub_domains_updated_at BEFORE UPDATE ON public.pub_domains FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();


--
-- Name: pub_domains pub_domains_fk; Type: FK CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.pub_domains
    ADD CONSTRAINT pub_domains_fk FOREIGN KEY (crawl_result) REFERENCES public.crawl_results(id);


--
-- PostgreSQL database dump complete
--

