--
-- PostgreSQL database dump
--

\restrict JKp5YQaGRP9rXUuZrZaUKyOwDay6IgioWAg6XspDYhJUzSzXrlxdPkxmIu7jXkL

-- Dumped from database version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)
-- Dumped by pg_dump version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: store_apps; Type: TABLE; Schema: public; Owner: james
--

CREATE TABLE public.store_apps (
    id integer NOT NULL,
    developer integer,
    name character varying,
    store_id character varying NOT NULL,
    store integer NOT NULL,
    category character varying,
    free boolean,
    price double precision,
    size text,
    minimum_android text,
    developer_email text,
    store_last_updated timestamp without time zone,
    content_rating text,
    ad_supported boolean,
    in_app_purchases boolean,
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    crawl_result integer,
    icon_url_512 character varying,
    release_date date,
    featured_image_url character varying,
    phone_image_url_1 character varying,
    phone_image_url_2 character varying,
    phone_image_url_3 character varying,
    tablet_image_url_1 character varying,
    tablet_image_url_2 character varying,
    tablet_image_url_3 character varying,
    textsearchable_index_col tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, (COALESCE(name, ''::character varying))::text)) STORED,
    additional_html_scraped_at timestamp without time zone,
    icon_url_100 text
);


ALTER TABLE public.store_apps OWNER TO james;

--
-- Name: store_apps_id_seq; Type: SEQUENCE; Schema: public; Owner: james
--

ALTER TABLE public.store_apps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_apps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_apps store_apps_pkey; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.store_apps
    ADD CONSTRAINT store_apps_pkey PRIMARY KEY (id);


--
-- Name: store_apps store_apps_un; Type: CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.store_apps
    ADD CONSTRAINT store_apps_un UNIQUE (store, store_id);


--
-- Name: store_apps_developer_idx; Type: INDEX; Schema: public; Owner: james
--

CREATE INDEX store_apps_developer_idx ON public.store_apps USING btree (developer);


--
-- Name: store_apps_name_idx; Type: INDEX; Schema: public; Owner: james
--

CREATE INDEX store_apps_name_idx ON public.store_apps USING gin (to_tsvector('simple'::regconfig, (name)::text));


--
-- Name: store_apps_store_id_idx; Type: INDEX; Schema: public; Owner: james
--

CREATE INDEX store_apps_store_id_idx ON public.store_apps USING btree (store_id);


--
-- Name: store_apps_updated_at_idx; Type: INDEX; Schema: public; Owner: james
--

CREATE INDEX store_apps_updated_at_idx ON public.store_apps USING btree (updated_at);


--
-- Name: textsearch_generated_idx; Type: INDEX; Schema: public; Owner: james
--

CREATE INDEX textsearch_generated_idx ON public.store_apps USING gin (textsearchable_index_col);


--
-- Name: store_apps store_app_audit; Type: TRIGGER; Schema: public; Owner: james
--

CREATE TRIGGER store_app_audit AFTER INSERT OR DELETE OR UPDATE ON public.store_apps FOR EACH ROW EXECUTE FUNCTION public.process_store_app_audit();


--
-- Name: store_apps store_apps_updated_at; Type: TRIGGER; Schema: public; Owner: james
--

CREATE TRIGGER store_apps_updated_at BEFORE UPDATE ON public.store_apps FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();


--
-- Name: store_apps store_apps_fk; Type: FK CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.store_apps
    ADD CONSTRAINT store_apps_fk FOREIGN KEY (store) REFERENCES public.stores(id);


--
-- Name: store_apps store_apps_fk_03; Type: FK CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.store_apps
    ADD CONSTRAINT store_apps_fk_03 FOREIGN KEY (crawl_result) REFERENCES public.crawl_results(id);


--
-- Name: store_apps store_apps_fk_1; Type: FK CONSTRAINT; Schema: public; Owner: james
--

ALTER TABLE ONLY public.store_apps
    ADD CONSTRAINT store_apps_fk_1 FOREIGN KEY (developer) REFERENCES public.developers(id);


--
-- PostgreSQL database dump complete
--

\unrestrict JKp5YQaGRP9rXUuZrZaUKyOwDay6IgioWAg6XspDYhJUzSzXrlxdPkxmIu7jXkL

