--
-- PostgreSQL database dump
--

\restrict wDANfIVctssZtAlKJEpbygiyKTAGYKJFqZ1nlaRChrpY9lKcZ6w2PFixpZCymDN

-- Dumped from database version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: store_apps_country_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_apps_country_history (
    store_app integer NOT NULL,
    review_count double precision,
    rating double precision,
    crawled_date date,
    rating_count integer,
    histogram bigint [] DEFAULT ARRAY[]::integer [],
    installs bigint,
    id integer NOT NULL,
    country_id smallint,
    store_last_updated date
);


ALTER TABLE public.store_apps_country_history OWNER TO postgres;

--
-- Name: store_apps_country_history_idx_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_apps_country_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_apps_country_history_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_apps_country_history store_apps_country_history_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_apps_country_history
ADD CONSTRAINT store_apps_country_history_pk PRIMARY KEY (id);


--
-- Name: store_apps_country_history_store_app_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX store_apps_country_history_store_app_idx ON public.store_apps_country_history USING btree (
    store_app
);


--
-- Name: store_apps_country_history_unique_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX store_apps_country_history_unique_idx ON public.store_apps_country_history USING btree (
    store_app, country_id, crawled_date
);


--
-- Name: store_apps_country_history fk_country; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_apps_country_history
ADD CONSTRAINT fk_country FOREIGN KEY (
    country_id
) REFERENCES public.countries (id);


--
-- Name: store_apps_country_history store_apps_country_history_app_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_apps_country_history
ADD CONSTRAINT store_apps_country_history_app_fk FOREIGN KEY (
    store_app
) REFERENCES public.store_apps (id);


--
-- PostgreSQL database dump complete
--

\unrestrict wDANfIVctssZtAlKJEpbygiyKTAGYKJFqZ1nlaRChrpY9lKcZ6w2PFixpZCymDN
