--
-- PostgreSQL database dump
--

\restrict bua7Vtbs25NlxpbxcTTxhWARaIcqmIH98ILhLYbgfE9d1VD0yaWaYCDH7JFnUWg

-- Dumped from database version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: store_collections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_collections (
    id smallint NOT NULL,
    store smallint NOT NULL,
    collection character varying NOT NULL
);


ALTER TABLE public.store_collections OWNER TO postgres;

--
-- Name: store_collections_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_collections store_collections_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_collections
ADD CONSTRAINT store_collections_pk PRIMARY KEY (id);


--
-- Name: store_collections store_collections_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_collections
ADD CONSTRAINT store_collections_un UNIQUE (store, collection);


--
-- Name: store_collections store_collections_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_collections
ADD CONSTRAINT store_collections_fk FOREIGN KEY (
    store
) REFERENCES public.stores (id);


--
-- PostgreSQL database dump complete
--

\unrestrict bua7Vtbs25NlxpbxcTTxhWARaIcqmIH98ILhLYbgfE9d1VD0yaWaYCDH7JFnUWg
