--
-- PostgreSQL database dump
--

\restrict RyjLyawpNMxVwO4YW3Y22c0eNMiaTOxlB9tAnBPnoHHtDypPiDyYLdnJxhHXp5l

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: store_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_categories (
    id smallint NOT NULL,
    store smallint NOT NULL,
    category character varying NOT NULL
);


ALTER TABLE public.store_categories OWNER TO postgres;

--
-- Name: store_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.store_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_categories store_categories_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_categories
    ADD CONSTRAINT store_categories_pk PRIMARY KEY (id);


--
-- Name: store_categories store_categories_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_categories
    ADD CONSTRAINT store_categories_un UNIQUE (store, category);


--
-- Name: store_categories store_categories_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_categories
    ADD CONSTRAINT store_categories_fk FOREIGN KEY (store) REFERENCES public.stores(id);


--
-- PostgreSQL database dump complete
--

\unrestrict RyjLyawpNMxVwO4YW3Y22c0eNMiaTOxlB9tAnBPnoHHtDypPiDyYLdnJxhHXp5l

