--
-- PostgreSQL database dump
--

\restrict FwfcZ7mQQI07epbaTNOVr2iLXHgvHm3Tal9WaKx1JnI1gxdK18d0a7xAiOPeLGK

-- Dumped from database version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: version_manifests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.version_manifests (
    id integer NOT NULL,
    version_code integer NOT NULL,
    manifest_string text NOT NULL
);


ALTER TABLE public.version_manifests OWNER TO postgres;

--
-- Name: version_manifests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.version_manifests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.version_manifests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: version_manifests version_manifests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_manifests
ADD CONSTRAINT version_manifests_pkey PRIMARY KEY (id);


--
-- Name: version_manifests version_manifests_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_manifests
ADD CONSTRAINT version_manifests_un UNIQUE (version_code);


--
-- Name: version_manifests fk_vm_version_code; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_manifests
ADD CONSTRAINT fk_vm_version_code FOREIGN KEY (
    version_code
) REFERENCES public.version_codes (id);


--
-- PostgreSQL database dump complete
--

\unrestrict FwfcZ7mQQI07epbaTNOVr2iLXHgvHm3Tal9WaKx1JnI1gxdK18d0a7xAiOPeLGK
