--
-- PostgreSQL database dump
--

\restrict QTGi5nxLo3Aa0oXlMe9A0kkrglVSLfCkPF9kLB67Y1sKi3GydKiBtubo4uwKMeL

-- Dumped from database version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: version_details_map; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.version_details_map (
    id bigint NOT NULL,
    version_code bigint,
    string_id integer
);


ALTER TABLE public.version_details_map OWNER TO postgres;

--
-- Name: version_details_map_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.version_details_map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.version_details_map_id_seq
    START WITH 49502675
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1
);


--
-- Name: version_details_map version_details_map_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_details_map
    ADD CONSTRAINT version_details_map_pkey PRIMARY KEY (id);


--
-- Name: version_details_map version_details_map_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_details_map
    ADD CONSTRAINT version_details_map_unique UNIQUE (version_code, string_id);


--
-- Name: version_details_map version_details_map_string_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_details_map
    ADD CONSTRAINT version_details_map_string_id_fkey FOREIGN KEY (string_id) REFERENCES public.version_strings(id);


--
-- PostgreSQL database dump complete
--

\unrestrict QTGi5nxLo3Aa0oXlMe9A0kkrglVSLfCkPF9kLB67Y1sKi3GydKiBtubo4uwKMeL

