--
-- PostgreSQL database dump
--

\restrict auvDJefqO2PyojPyqnQ0LI0J9BeBsLCfiifn2F9o2wDqDp8VX5ZyKeSYCHX9gcH

-- Dumped from database version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)
-- Dumped by pg_dump version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: version_strings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.version_strings (
    id integer NOT NULL,
    xml_path text NOT NULL,
    tag text,
    value_name text NOT NULL
);


ALTER TABLE public.version_strings OWNER TO postgres;

--
-- Name: version_strings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.version_strings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.version_strings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: version_strings version_strings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_strings
    ADD CONSTRAINT version_strings_pkey PRIMARY KEY (id);


--
-- Name: version_strings version_strings_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_strings
    ADD CONSTRAINT version_strings_unique UNIQUE (xml_path, tag, value_name);


--
-- Name: version_strings_value_name_lower_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX version_strings_value_name_lower_idx ON public.version_strings USING btree (lower(value_name) text_pattern_ops);


--
-- Name: version_strings_value_name_lower_prefix_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX version_strings_value_name_lower_prefix_idx ON public.version_strings USING btree (lower(value_name) text_pattern_ops);


--
-- Name: version_strings_value_name_trgm_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX version_strings_value_name_trgm_idx ON public.version_strings USING gin (lower(value_name) public.gin_trgm_ops);


--
-- Name: version_strings_xml_path_lower_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX version_strings_xml_path_lower_idx ON public.version_strings USING btree (lower(xml_path));


--
-- Name: version_strings_xml_path_trgm_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX version_strings_xml_path_trgm_idx ON public.version_strings USING gin (lower(xml_path) public.gin_trgm_ops);


--
-- PostgreSQL database dump complete
--

\unrestrict auvDJefqO2PyojPyqnQ0LI0J9BeBsLCfiifn2F9o2wDqDp8VX5ZyKeSYCHX9gcH

