--
-- PostgreSQL database dump
--

\restrict IULBcS82Te1OHGEZaYvNvdbhjQMAvjv3brKmsutOeJbpfYgQCa3R4mHeJRU6bsd

-- Dumped from database version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)
-- Dumped by pg_dump version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: version_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.version_codes (
    id integer NOT NULL,
    store_app integer NOT NULL,
    version_code character varying NOT NULL,
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    crawl_result smallint NOT NULL,
    apk_hash character varying(32),
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now())
);


ALTER TABLE public.version_codes OWNER TO postgres;

--
-- Name: version_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.version_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.version_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: version_codes version_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_codes
ADD CONSTRAINT version_codes_pkey PRIMARY KEY (id);


--
-- Name: version_codes version_codes_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_codes
ADD CONSTRAINT version_codes_un UNIQUE (store_app, version_code);


--
-- Name: version_codes version_codes_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER version_codes_updated_at BEFORE UPDATE ON public.version_codes FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();


--
-- Name: version_codes vc_fk_store_app; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_codes
ADD CONSTRAINT vc_fk_store_app FOREIGN KEY (
    store_app
) REFERENCES public.store_apps (id);


--
-- PostgreSQL database dump complete
--

\unrestrict IULBcS82Te1OHGEZaYvNvdbhjQMAvjv3brKmsutOeJbpfYgQCa3R4mHeJRU6bsd
