--
-- PostgreSQL database dump
--

\restrict vVVXMwLbMVLZ6kPOucCf5wu7nSSXfSCTTbaXyfZEchS4fLv3ZbxbOHleGDWJgsO

-- Dumped from database version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-2.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: version_strings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.version_strings (
    id integer NOT NULL,
    xml_path text NOT NULL,
    tag text,
    value_name text NOT NULL
);


ALTER TABLE public.version_strings OWNER TO postgres;

--
-- Name: version_strings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.version_strings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.version_strings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: version_strings version_strings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_strings
ADD CONSTRAINT version_strings_pkey PRIMARY KEY (id);


--
-- Name: version_strings version_strings_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.version_strings
ADD CONSTRAINT version_strings_unique UNIQUE (xml_path, tag, value_name);


--
-- PostgreSQL database dump complete
--

\unrestrict vVVXMwLbMVLZ6kPOucCf5wu7nSSXfSCTTbaXyfZEchS4fLv3ZbxbOHleGDWJgsO
