name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on main branch push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Deploy to my server
        uses: appleboy/ssh-action@master
        env:
          TARGETDIR: ${{ secrets.TARGET_DIR }}
        with:
          host: ${{ secrets.HOST_DNS }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.HOST_DNS }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          envs: TARGETDIR
          protocol: tcp4
          script: |
            cd $TARGETDIR
            pwd
            git pull origin main
